apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: ldap-service
  labels:
    app: "ldap"
spec:
  type: LoadBalancer
  ports:
  - name: ldap
    nodePort: 31430
    port: 389
    protocol: TCP
    targetPort: 389
  selector:
    app: "ldap"
 
