apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-mq
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/vcailly/tekton-mq
