apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: demo
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - port: 3300
      name: app
#      nodePort: 32426
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: ibm-cr-secret
      containers:
      - name: app
        image: IMAGE
        ports:
        - containerPort: 3300
