apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ibm-mq-dev-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities:
- CHOWN
- FOWNER
- SETGID
- SETUID
- AUDIT_WRITE
- DAC_OVERRIDE
allowedFlexVolumes: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
supplementalGroups:
  ranges:
  - max: 65535
    min: 1
  type: MustRunAs
volumes:
- secret
- persistentVolumeClaim
users: []
priority: 0
---

