apiVersion: v1
kind: Pod
metadata:
  name: mq-bakup
  namespace: demo
spec:
  serviceAccountName: default
  imagePullSecrets:
  - name: ibm-cr-secret
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-mqtest-ibm-mq-0
  - name: mqtest-ibm-mq-log
    persistentVolumeClaim:
      claimName: mqtest-ibm-mq-log
  - name: mqtest-ibm-mq-qm
    persistentVolumeClaim:
      claimName: mqtest-ibm-mq-qm
  - name: ibm-mq-bkup
    persistentVolumeClaim:
      claimName: ibm-mq-bkup
  containers:
  - name: mq-bkup-ctr
    image: vcailly/k8s-kubectl:1.0
    volumeMounts:
    - mountPath: "/mnt/mqm"
      name: data
    - mountPath: "/mnt/mqm-log"
      name: mqtest-ibm-mq-log
    - mountPath: "/mnt/mqm-data"
      name: mqtest-ibm-mq-qm
    - mountPath: "/mnt/mqm-bkup"
      name: ibm-mq-bkup
    imagePullPolicy: Always
    env:
    - name: MQ_QMGR_NAME
      value: BSM
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["sleep"]
    args: ["3600"]

